In [1]:
import numpy as np

In [7]:
escalar = 5.679
vector = np.array([1, 2, 3])
matriz = np.array([[1, 2], [3, 4]])
tensor = np.array([
    [[1,2,3], [4,5,6], [7,8,9]], 
    [[6,7,8], [0,0,0], [9,10,11]],
    [[10,11,12], [13,14,15], [17,18,19]],
])


In [8]:
print("Escalar:", escalar)

Escalar: 5.679


In [10]:
vector.shape

(3,)

In [11]:
print("Vector", vector)

Vector [1 2 3]


In [12]:
len(vector)

3

In [13]:
matriz.shape


(2, 2)

In [14]:
print("Matriz", matriz)

Matriz [[1 2]
 [3 4]]


In [15]:
len(matriz)

2

In [16]:
print(matriz.size)

4


In [19]:
print("Tensor", tensor)

Tensor [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 6  7  8]
  [ 0  0  0]
  [ 9 10 11]]

 [[10 11 12]
  [13 14 15]
  [17 18 19]]]


In [20]:
print("Tensor", tensor.shape)

Tensor (3, 3, 3)


In [21]:
print("Tensor", tensor.size)

Tensor 27
