In [1]:
import numpy as np

In [ ]:
escalar = 5.679
vector = np.array([1, 2, 3])
matriz = np.array([[1, 2], [3, 4], [5, 6]])
tensor = np.array([
    [[1,2,3,5], 
     [4,5,6,7], 
     [7,8,9,12]], 
    [[6,7,8,9], 
     [0,0,0,3], 
     [9,10,11,13]],
    [[10,11,12,15], [13,14,15,18], [17,18,19,20]],
])


In [8]:
vector_t= vector.T
print("Transpuesta del vector:")
print(vector_t)

Transpuesta del vector:
[1 2 3]


In [9]:
matriz_t = matriz.T
print("\nTranspuesta de la matriz:")
print(matriz_t)


Transpuesta de la matriz:
[[1 3 5]
 [2 4 6]]


In [10]:
tensor_t = tensor.T
print("\nTranspuesta del tensor:")
print(tensor_t)


Transpuesta del tensor:
[[[ 1  6 10]
  [ 4  0 13]
  [ 7  9 17]]

 [[ 2  7 11]
  [ 5  0 14]
  [ 8 10 18]]

 [[ 3  8 12]
  [ 6  0 15]
  [ 9 11 19]]

 [[ 5  9 15]
  [ 7  3 18]
  [12 13 20]]]


In [12]:
A = np.array([[1, 2], 
              [3, 4], 
              [5, 6]])
B = np.array([[7, 8], 
              [9, 10], 
              [11, 12]])
C = A + B
print("\nSuma de matrices A y B:")
print(C)

              


Suma de matrices A y B:
[[ 8 10]
 [12 14]
 [16 18]]


In [13]:
D = matriz + escalar
print("\nSuma de la matriz con el escalar:")
print(D)


Suma de la matriz con el escalar:
[[ 6.679  7.679]
 [ 8.679  9.679]
 [10.679 11.679]]
