In [11]:
import numpy as np

In [7]:
escalar = 5.679
vector = np.array([1, 2])
matriz = np.array([[1, 2], [3, 4], [5, 6]])
tensor = np.array([
    [[1,2,3,5], 
     [4,5,6,7], 
     [7,8,9,12]], 
    [[6,7,8,9], 
     [0,0,0,3], 
     [9,10,11,13]],
    [[10,11,12,15], [13,14,15,18], [17,18,19,20]],
])

In [12]:
A = matriz * vector
print("Producto de la matriz con el vector:")
print(A)

Producto de la matriz con el vector:
[[ 1  4]
 [ 3  8]
 [ 5 12]]


In [13]:
B = matriz.dot(vector) 
print("\nProducto interno de la matriz con el vector:")
print(B)


Producto interno de la matriz con el vector:
[ 5 11 17]


In [14]:
C = np.dot(matriz, vector)
print("\nProducto interno de la matriz con el vector usando np.dot:")
print(C)


Producto interno de la matriz con el vector usando np.dot:
[ 5 11 17]
