In [1]:
import numpy as np

In [3]:
A = np.array([[1, 2], 
              [4, 5], 
              [7, 8],
              ])
B = np.array([[1, 2], 
              [3, 4], 
              ])
C = np.array([[4, 5], 
              [7, 8],
              ])


In [4]:
# Asociativa C1 = A.dot(B).dot(C)
C1 = (A.dot(B)).dot(C)
print("Producto interno asociativo (A.B).C:")
print(C1) 

Producto interno asociativo (A.B).C:
[[ 98 115]
 [272 319]
 [446 523]]


In [5]:
# Asociativa C2 = A.dot(B.dot(C))
C2 = A.dot(B.dot(C))
print("Producto interno asociativo A.(B.C):")
print(C2)

Producto interno asociativo A.(B.C):
[[ 98 115]
 [272 319]
 [446 523]]


In [6]:
# Distributiva Producto interno distributivo A.B + A.C
D = A.dot(B) + A.dot(C)
print("Producto interno distributivo A.B + A.C:")
print(D)

Producto interno distributivo A.B + A.C:
[[ 25  31]
 [ 70  88]
 [115 145]]


In [7]:
# Distributiva alternativa Producto interno distributivo A.(B+C)
E = A.dot(B + C)
print("Producto interno distributivo A.(B+C):")
print(E)

Producto interno distributivo A.(B+C):
[[ 25  31]
 [ 70  88]
 [115 145]]


In [8]:
# Commutativa Transpuesta del producto interno (A.B).T = B.T.A.T
F1 = (A.dot(B)).T   