In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], 
              [4, 5], 
              [7, 8],
              ])
B = np.array([[1, 2], 
              [3, 4], 
              ])
C = np.array([[4, 5], 
              [7, 8],
              ])

In [4]:
#Calcular la transpuesta del producto interno de A con B
print((A @ B).T)

#Calcular el producto interno de la transpuesta de B con la transpuesta de A
print(B.T @ A.T)    

#Validar si son iguales
print(np.array_equal((A @ B).T, B.T @ A.T))

[[ 7 19 31]
 [10 28 46]]
[[ 7 19 31]
 [10 28 46]]
True
