In [1]:
#Vamos a visualizar las caracteristicas de las matrices Identidad, Inversa y Singular, asi como sus propiedades.
import numpy as np


In [3]:
#Genera la matriz identidad de 4x4
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
#Genera un vecor b de 4x1
b = np.array([[1], [2], [3], [4]])
print(b)

#Multiplica la matriz identidad por el vector b
print(I @ b)

[[1]
 [2]
 [3]
 [4]]
[[1.]
 [2.]
 [3.]
 [4.]]


In [8]:
#Calcula la inversa de una matriz A de 3x3
A = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
print(A)
A_inv = np.linalg.inv(A)
print(A_inv)

[[1 2 3]
 [0 1 4]
 [5 6 0]]
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [10]:
#Valida si la multiplicacion de A por su inversa es igual a la matriz identidad
print(np.array_equal(A @ A_inv, np.eye(3)))

False
