In [1]:
#Vamos a resolver un sistema de ecuacioneslineales utilizando el metodo de la matriz inversa.
#Vamos a comprobar la solucion graficamente.
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#En caso de encontrar un valor muy cercano a cero, se puede considerar como cero.
np.set_printoptions(suppress=True)

In [3]:
A = np.array([[3, 1], [2, 1]])
print("Matriz A:")
print(A)

Matriz A:
[[3 1]
 [2 1]]


In [4]:
b = np.array([[1], [1]])
print("Vector b:")
print(b)

Vector b:
[[1]
 [1]]


In [5]:
#Calcular la inversa de la matriz A
A_inv = np.linalg.inv(A)
print("Inversa de A:")
print(A_inv)

Inversa de A:
[[ 1. -1.]
 [-2.  3.]]


In [6]:
#Resolver el sistema de ecuaciones Ax = b utilizando la matriz inversa
x = A_inv @ b
print("Solucion x:")
print(x)

Solucion x:
[[0.]
 [1.]]
