In [2]:
import numpy as np


In [3]:
vector = np.array([1,2,3,4,5])
matriz = np.diag(vector)
print(matriz)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [4]:
print(matriz[0:4,0:3])

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


In [5]:
print(matriz[0:3,0:4])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [6]:
A = np.diag([2,3,4,5])
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [11]:
v1 = np.array([[1,1,1,1]])
print(v1)
print(A.dot(v1.T))

[[1 1 1 1]]
[[2]
 [3]
 [4]
 [5]]


In [12]:
A_inv = np.diag([1/2,1/3,1/4,1/5])
print(A_inv)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [14]:
identidad = A @ A_inv
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
A_inv_calc = np.linalg.inv(A)
print(A_inv_calc)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [ ]:
escalar = 3.1

print(type(escalar))
# Salida: <class 'float'>

AttributeError: 'float' object has no attribute 'shape'

In [2]:
import numpy as np

# Un escalar de NumPy (arreglo de 0 dimensiones)
np_escalar = np.array(3.1)

print(type(np_escalar))
# Salida: <class 'numpy.ndarray'>

print(np_escalar.shape)
# Salida: ()  (una tupla vacía, indicando 0 dimensiones)


<class 'numpy.ndarray'>
()
