In [2]:
import numpy as np

In [4]:
matriz = np.array([[1,0,0],
                   [0,1,0],
                   [0,0,1]
                   ])

print(matriz)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [5]:
print(matriz[:,0].dot(matriz[:,1]))

0


In [6]:
print(matriz[:,0].dot(matriz[:,2]))

0


In [7]:
print(matriz[:,1].dot(matriz[:,2]))

0


In [8]:
print(np.linalg.norm(matriz[:,0]))
print(np.linalg.norm(matriz[:,1]))
print(np.linalg.norm(matriz[:,2]))

1.0
1.0
1.0


In [10]:
print(matriz[0,:].dot(matriz[1,:]))
print(matriz[0,:].dot(matriz[2,:]))
print(matriz[1,:].dot(matriz[2,:]))

0
0
0


In [11]:
print(np.linalg.norm(matriz[0,:]))
print(np.linalg.norm(matriz[1,:]))
print(np.linalg.norm(matriz[2,:]))

1.0
1.0
1.0


In [16]:
A = np.array([[np.cos(100), -np.sin(100)],
              [np.sin(100), np.cos(100)]])

print(A)

[[ 0.86231887  0.50636564]
 [-0.50636564  0.86231887]]


In [17]:
print(np.linalg.norm(A[0,:]))
print(np.linalg.norm(A[1,:]))
print(np.linalg.norm(A[:,0]))
print(np.linalg.norm(A[:,1]))

0.9999999999999999
0.9999999999999999
0.9999999999999999
0.9999999999999999


In [19]:
print(A[0,:].dot(A[1,:]))
print(A[:,0].dot(A[:,1]))

0.0
0.0


In [20]:
A_T = A.T
print(A_T.dot(A))
print(A.dot(A_T))

[[ 1.00000000e+00 -7.93771519e-18]
 [-7.93771519e-18  1.00000000e+00]]
[[1.00000000e+00 7.93771519e-18]
 [7.93771519e-18 1.00000000e+00]]


In [21]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]


In [22]:
print(A_T)

[[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]


In [25]:
print(1/A_T.dot(A))

[[ 1.00000000e+00 -1.25980837e+17]
 [-1.25980837e+17  1.00000000e+00]]
